
default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rugbydata
  username: rugbyown
  password: J0hn$m1%hl@y$
  host: localhost

test:
  <<: *default
  database: rugbydata
  host: localhost

production:
  <<: *default
  database: rugbydata
  username: rugbyown
  password: <%= ENV["RUGBYDATA_DATABASE_PASSWORD"] %>
  host: localhost
