
default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rugbydata
  username: rugbyown
  password: development1234
  host: localhost

test:
  <<: *default
  database: test_rugbydata
  username: test_rugbyown
  password: test1234
  host: localhost

production:
  <<: *default
  database: rugbydata
  username: rugbyown
  password: <%= ENV["RUGBYDATA_DATABASE_PASSWORD"] %>
  host: localhost